/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

// note that for Email,Ip address and Linkedin enter the full details to activate the "SAVE" button

import Model.Product;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author nemod
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Product product;
    private BufferedImage disp_image;
    
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblname = new javax.swing.JLabel();
        lblgeographicdata = new javax.swing.JLabel();
        lbltelephone = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmedicalnumber = new javax.swing.JLabel();
        lblhealthplannumber = new javax.swing.JLabel();
        lblbankaccount = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbllicense = new javax.swing.JLabel();
        lblvehicleidentifier = new javax.swing.JLabel();
        lbldeviceidentifiers = new javax.swing.JLabel();
        lbllinkedIn = new javax.swing.JLabel();
        lblipaddress = new javax.swing.JLabel();
        lbluniquecode = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtgeographicdata = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txthealthplannumber = new javax.swing.JTextField();
        txtbankaccount = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicleidentifier = new javax.swing.JTextField();
        txtdeviceidentifiers = new javax.swing.JTextField();
        txtlinkedIn = new javax.swing.JTextField();
        txtipaddress = new javax.swing.JTextField();
        txtuniquecode = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnsave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtmed = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jname = new javax.swing.JLabel();
        jgeo = new javax.swing.JLabel();
        jtel = new javax.swing.JLabel();
        jfax = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jssn = new javax.swing.JLabel();
        jmed = new javax.swing.JLabel();
        jhealth = new javax.swing.JLabel();
        jbank = new javax.swing.JLabel();
        jlc = new javax.swing.JLabel();
        jveh = new javax.swing.JLabel();
        jdev = new javax.swing.JLabel();
        jlink = new javax.swing.JLabel();
        jip = new javax.swing.JLabel();
        jun = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 68, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name:");
        add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        lblgeographicdata.setForeground(new java.awt.Color(255, 255, 255));
        lblgeographicdata.setText("Geographical:");
        add(lblgeographicdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        lbltelephone.setForeground(new java.awt.Color(255, 255, 255));
        lbltelephone.setText("Telephone:");
        add(lbltelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        lblfax.setForeground(new java.awt.Color(255, 255, 255));
        lblfax.setText("Fax:");
        add(lblfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("Email:");
        add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        lblssn.setForeground(new java.awt.Color(255, 255, 255));
        lblssn.setText("SSN:");
        add(lblssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        lblmedicalnumber.setForeground(new java.awt.Color(255, 255, 255));
        lblmedicalnumber.setText("Medical record number:");
        add(lblmedicalnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        lblhealthplannumber.setForeground(new java.awt.Color(255, 255, 255));
        lblhealthplannumber.setText("Health plan number:");
        add(lblhealthplannumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        lblbankaccount.setForeground(new java.awt.Color(255, 255, 255));
        lblbankaccount.setText("Bank account numbers:");
        add(lblbankaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date:");
        add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        lbllicense.setForeground(new java.awt.Color(255, 255, 255));
        lbllicense.setText("Certificate/license number:");
        add(lbllicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        lblvehicleidentifier.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicleidentifier.setText("Vehicle identifiers:");
        add(lblvehicleidentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        lbldeviceidentifiers.setForeground(new java.awt.Color(255, 255, 255));
        lbldeviceidentifiers.setText("Device identifiers:");
        add(lbldeviceidentifiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        lbllinkedIn.setForeground(new java.awt.Color(255, 255, 255));
        lbllinkedIn.setText("LinkedIn:");
        add(lbllinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        lblipaddress.setForeground(new java.awt.Color(255, 255, 255));
        lblipaddress.setText("Internet protocol addresses:");
        add(lblipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        lbluniquecode.setForeground(new java.awt.Color(255, 255, 255));
        lbluniquecode.setText("Unique identifying number:");
        add(lbluniquecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));

        lblphoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblphoto.setForeground(new java.awt.Color(255, 255, 255));
        lblphoto.setText("Photo:");
        add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        lblTitle.setBackground(new java.awt.Color(255, 51, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(379, 379, 379))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        txtgeographicdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgeographicdataKeyReleased(evt);
            }
        });
        add(txtgeographicdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 312, -1));

        txttelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelephoneKeyReleased(evt);
            }
        });
        add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 312, -1));

        txtfax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfaxKeyReleased(evt);
            }
        });
        add(txtfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 312, -1));

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 312, -1));

        txtssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtssnKeyReleased(evt);
            }
        });
        add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 312, -1));

        txthealthplannumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthealthplannumberKeyReleased(evt);
            }
        });
        add(txthealthplannumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 312, -1));

        txtbankaccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbankaccountKeyReleased(evt);
            }
        });
        add(txtbankaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 312, -1));

        txtlicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlicenseKeyReleased(evt);
            }
        });
        add(txtlicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 312, -1));

        txtvehicleidentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvehicleidentifierKeyReleased(evt);
            }
        });
        add(txtvehicleidentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 312, -1));

        txtdeviceidentifiers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdeviceidentifiersKeyReleased(evt);
            }
        });
        add(txtdeviceidentifiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 312, -1));

        txtlinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlinkedInKeyReleased(evt);
            }
        });
        add(txtlinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 312, -1));

        txtipaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtipaddressKeyReleased(evt);
            }
        });
        add(txtipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 312, -1));

        txtuniquecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuniquecodeKeyReleased(evt);
            }
        });
        add(txtuniquecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 312, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 312, -1));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, -1));

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        txtmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmedKeyReleased(evt);
            }
        });
        add(txtmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 310, -1));

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, -1));
        add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 80, 20));
        add(jgeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 60, 20));
        add(jtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 70, 20));
        add(jfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 150, 20));
        add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 240, 20));
        add(jssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 180, 20));
        add(jmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 170, 20));
        add(jhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 160, 20));
        add(jbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 170, 20));
        add(jlc, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 180, 20));
        add(jveh, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 170, 20));
        add(jdev, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 170, 20));
        add(jlink, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 444, 220, 20));
        add(jip, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 170, 20));
        add(jun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 280, 20));
        add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 200, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        
        String NEW = "^[a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtgeographicdata.getText());
        if(!new1.matches()){
            jname.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jname.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_nameKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if(this.disp_image == null){
            JOptionPane.showMessageDialog(this,"Image is Mandatory ","Add the Image", JOptionPane.ERROR_MESSAGE);
        }
        savemethod();
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void savemethod(){
        product.setName(name.getText());
        
        product.setGeographicdata(txtgeographicdata.getText());
        
        product.setDate(jDateChooser1.getDate());
        
          //telephone
    long tel = Integer.parseInt(txttelephone.getText());
product.setTelephone(tel);

 //fax 
     long f = Integer.parseInt(txtfax.getText());
      product.setFax(f);
      
    //email
      product.setEmail(txtemail.getText()); 
      
       //SSN
     long s = Integer.parseInt(txtssn.getText());
    product.setSsn(s);  
    
    long MedNum = Integer.parseInt(txtmed.getText());
     product.setMedicalnumber(MedNum);
     
      long Health = Integer.parseInt(txthealthplannumber.getText());
  product.setHealthplannumber(Health);
  
  product.setBankaccount(txtbankaccount.getText());
  
   product.setLicense(txtlicense.getText());
   
    product.setVehicleidentifier(txtvehicleidentifier.getText());
    
    product.setDeviceidentifiers(txtdeviceidentifiers.getText());
    
    product.setLinkedIn(txtlinkedIn.getText());
    
   
    product.setIpaddress(txtipaddress.getText());
     
     //Uniquecode
      product.setUniquecode(txtuniquecode.getText());
      
      product.setFilename(jLabelImg.getIcon());

        
        JOptionPane.showMessageDialog(this,"Product Information Saved!");
    }
    private void txtgeographicdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgeographicdataKeyReleased
        // TODO add your handling code here:
        
         String NEW = "^[a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtgeographicdata.getText());
        if(!new1.matches()){
            jgeo.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jgeo.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtgeographicdataKeyReleased

    private void txttelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelephoneKeyReleased
        // TODO add your handling code here:
        String NEW = "^[0-9]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txttelephone.getText());
        if(!new1.matches()){
            jtel.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jtel.setText(null);
            btnsave.setEnabled(true);
        }
        
    }//GEN-LAST:event_txttelephoneKeyReleased

    private void txtfaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyReleased
        // TODO add your handling code here:
         String NEW = "^[0-9]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtfax.getText());
        if(!new1.matches()){
            jfax.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jfax.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtfaxKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
          String NEW = "^[a-zA-Z0-9.-_]{0,30}[@][a-zA-Z0-9]{0,5}[.][a-zA-Z]{0,10}[a-zA-Z]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtemail.getText());
        if(!new1.matches()){
            jemail.setText("enter full emailid");
            btnsave.setEnabled(false);
        }
        else{
            jemail.setText(null);
            btnsave.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtssnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyReleased
        // TODO add your handling code here:
        
         String NEW = "^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtssn.getText());
        if(!new1.matches()){
            jssn.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jssn.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtssnKeyReleased

    private void txtmedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedKeyReleased
        // TODO add your handling code here:
        
        String NEW = "^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtmed.getText());
        if(!new1.matches()){
            jmed.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jmed.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtmedKeyReleased

    private void txthealthplannumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthealthplannumberKeyReleased
        // TODO add your handling code here:
         String NEW = "^[0-9]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txthealthplannumber.getText());
        if(!new1.matches()){
            jhealth.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jhealth.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txthealthplannumberKeyReleased

    private void txtbankaccountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbankaccountKeyReleased
        // TODO add your handling code here:
          String NEW = "^[a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtbankaccount.getText());
        if(!new1.matches()){
            jbank.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jbank.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtbankaccountKeyReleased

    private void txtlicenseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenseKeyReleased
        // TODO add your handling code here:
         String NEW = "^[a-zA-Z0-9]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtlicense.getText());
        if(!new1.matches()){
            jlc.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jlc.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtlicenseKeyReleased

    private void txtvehicleidentifierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehicleidentifierKeyReleased
        // TODO add your handling code here:
        String NEW = "^[a-zA-Z0-9]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtvehicleidentifier.getText());
        if(!new1.matches()){
            jveh.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jveh.setText(null);
            btnsave.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtvehicleidentifierKeyReleased

    private void txtdeviceidentifiersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeviceidentifiersKeyReleased
        // TODO add your handling code here:
         String NEW = "^[a-zA-Z0-9]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtdeviceidentifiers.getText());
        if(!new1.matches()){
            jdev.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jdev.setText(null);
            btnsave.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtdeviceidentifiersKeyReleased

    private void txtlinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlinkedInKeyReleased
        // TODO add your handling code here:
        
        String NEW = "^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$";;
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtlinkedIn.getText());
        if(!new1.matches()){
            jlink.setText("enter full link");
            btnsave.setEnabled(false);
        }
        else{
            jlink.setText(null);
            btnsave.setEnabled(true);
        }
    }//GEN-LAST:event_txtlinkedInKeyReleased

    private void txtipaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtipaddressKeyReleased
        // TODO add your handling code here:
         String NEW = "^\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtipaddress.getText());
        if(!new1.matches()){
            jip.setText("enter full IP Address");
            btnsave.setEnabled(false);
        }
        else{
            jip.setText(null);
            btnsave.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_txtipaddressKeyReleased

    private void txtuniquecodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuniquecodeKeyReleased
        // TODO add your handling code here:
        String NEW = "^[0-9]{0,30}[.]{0,10}$";
        Pattern patt = Pattern.compile(NEW);
        Matcher new1 = patt.matcher(txtuniquecode.getText());
        if(!new1.matches()){
            jun.setText("something went wrong");
            btnsave.setEnabled(false);
        }
        else{
            jun.setText(null);
            btnsave.setEnabled(true);
        }
        
    }//GEN-LAST:event_txtuniquecodeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.disp_image = null;
        JFileChooser chooser = new JFileChooser();
        
        FileNameExtensionFilter fe = new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        chooser.addChoosableFileFilter(fe);
        
        int OpenDialogue = chooser.showSaveDialog(null);
        
        if(OpenDialogue == JFileChooser.APPROVE_OPTION){
            File ImageFile = chooser.getSelectedFile();
            
            try{
                this.disp_image = ImageIO.read(ImageFile);
                ImageIcon img = new ImageIcon(disp_image);
                Image Img = img.getImage().getScaledInstance(jLabelImg.getWidth(),jLabelImg.getHeight(), Image.SCALE_SMOOTH);
                jLabelImg.setIcon(new ImageIcon(Img));
            }catch (IOException ioe){
                JOptionPane.showMessageDialog(this, "Image is mandatory!");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbank;
    private javax.swing.JLabel jdev;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jfax;
    private javax.swing.JLabel jgeo;
    private javax.swing.JLabel jhealth;
    private javax.swing.JLabel jip;
    private javax.swing.JLabel jlc;
    private javax.swing.JLabel jlink;
    private javax.swing.JLabel jmed;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jssn;
    private javax.swing.JLabel jtel;
    private javax.swing.JLabel jun;
    private javax.swing.JLabel jveh;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbankaccount;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldeviceidentifiers;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblgeographicdata;
    private javax.swing.JLabel lblhealthplannumber;
    private javax.swing.JLabel lblipaddress;
    private javax.swing.JLabel lbllicense;
    private javax.swing.JLabel lbllinkedIn;
    private javax.swing.JLabel lblmedicalnumber;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltelephone;
    private javax.swing.JLabel lbluniquecode;
    private javax.swing.JLabel lblvehicleidentifier;
    private javax.swing.JTextField name;
    private javax.swing.JTextField txtbankaccount;
    private javax.swing.JTextField txtdeviceidentifiers;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txthealthplannumber;
    private javax.swing.JTextField txtipaddress;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedIn;
    private javax.swing.JTextField txtmed;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtuniquecode;
    private javax.swing.JTextField txtvehicleidentifier;
    // End of variables declaration//GEN-END:variables
}
