/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author nemod
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    Product product;
    
    public ViewJPanel(Product product) {
        initComponents();
        
        this.product = product;
        displayProduct();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblgeographicdata = new javax.swing.JLabel();
        lbltelephone = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmedicalnumber = new javax.swing.JLabel();
        lblhealthplannumber = new javax.swing.JLabel();
        lblbankaccount = new javax.swing.JLabel();
        lbllicense = new javax.swing.JLabel();
        lblvehicleidentifier = new javax.swing.JLabel();
        lbldeviceidentifiers = new javax.swing.JLabel();
        lbllinkedIn = new javax.swing.JLabel();
        lblipaddress = new javax.swing.JLabel();
        lbluniquecode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtgeographicdata = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtmed = new javax.swing.JTextField();
        txthealthplannumber = new javax.swing.JTextField();
        txtbankaccount = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicleidentifier = new javax.swing.JTextField();
        txtdeviceidentifiers = new javax.swing.JTextField();
        txtlinkedIn = new javax.swing.JTextField();
        txtipaddress = new javax.swing.JTextField();
        txtuniquecode = new javax.swing.JTextField();
        lbldate = new javax.swing.JLabel();
        PictureLabel = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jDateChooser1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 68, 80));

        jPanel2.setBackground(new java.awt.Color(44, 68, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblgeographicdata.setForeground(new java.awt.Color(255, 255, 255));
        lblgeographicdata.setText("Geographical:");
        jPanel2.add(lblgeographicdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        lbltelephone.setForeground(new java.awt.Color(255, 255, 255));
        lbltelephone.setText("Telephone:");
        jPanel2.add(lbltelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblfax.setForeground(new java.awt.Color(255, 255, 255));
        lblfax.setText("Fax:");
        jPanel2.add(lblfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("Email:");
        jPanel2.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        lblssn.setForeground(new java.awt.Color(255, 255, 255));
        lblssn.setText("SSN:");
        jPanel2.add(lblssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        lblmedicalnumber.setForeground(new java.awt.Color(255, 255, 255));
        lblmedicalnumber.setText("Medical record number:");
        jPanel2.add(lblmedicalnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        lblhealthplannumber.setForeground(new java.awt.Color(255, 255, 255));
        lblhealthplannumber.setText("Health plan number:");
        jPanel2.add(lblhealthplannumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        lblbankaccount.setForeground(new java.awt.Color(255, 255, 255));
        lblbankaccount.setText("Bank account numbers:");
        jPanel2.add(lblbankaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        lbllicense.setForeground(new java.awt.Color(255, 255, 255));
        lbllicense.setText("Certificate/license number:");
        jPanel2.add(lbllicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        lblvehicleidentifier.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicleidentifier.setText("Vehicle identifiers:");
        jPanel2.add(lblvehicleidentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        lbldeviceidentifiers.setForeground(new java.awt.Color(255, 255, 255));
        lbldeviceidentifiers.setText("Device identifiers:");
        jPanel2.add(lbldeviceidentifiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        lbllinkedIn.setForeground(new java.awt.Color(255, 255, 255));
        lbllinkedIn.setText("LinkedIn:");
        jPanel2.add(lbllinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        lblipaddress.setForeground(new java.awt.Color(255, 255, 255));
        lblipaddress.setText("Internet protocol addresses:");
        jPanel2.add(lblipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        lbluniquecode.setForeground(new java.awt.Color(255, 255, 255));
        lbluniquecode.setText("Unique identifying number:");
        jPanel2.add(lbluniquecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Photo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));
        jPanel2.add(txtgeographicdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 312, -1));
        jPanel2.add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 312, -1));
        jPanel2.add(txtfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 312, -1));
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 312, -1));
        jPanel2.add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 312, -1));
        jPanel2.add(txtmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 312, -1));
        jPanel2.add(txthealthplannumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 312, -1));
        jPanel2.add(txtbankaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 312, -1));
        jPanel2.add(txtlicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 312, -1));
        jPanel2.add(txtvehicleidentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 312, -1));
        jPanel2.add(txtdeviceidentifiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 312, -1));
        jPanel2.add(txtlinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 312, -1));
        jPanel2.add(txtipaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 312, -1));
        jPanel2.add(txtuniquecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 312, -1));

        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date:");
        jPanel2.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        PictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        PictureLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(PictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 250, 160));

        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name:");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 312, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 310, -1));

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW PAGE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(439, 439, 439))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 738, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JTextField jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblbankaccount;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldeviceidentifiers;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblgeographicdata;
    private javax.swing.JLabel lblhealthplannumber;
    private javax.swing.JLabel lblipaddress;
    private javax.swing.JLabel lbllicense;
    private javax.swing.JLabel lbllinkedIn;
    private javax.swing.JLabel lblmedicalnumber;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltelephone;
    private javax.swing.JLabel lbluniquecode;
    private javax.swing.JLabel lblvehicleidentifier;
    private javax.swing.JTextField txtbankaccount;
    private javax.swing.JTextField txtdeviceidentifiers;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txthealthplannumber;
    private javax.swing.JTextField txtipaddress;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedIn;
    private javax.swing.JTextField txtmed;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtuniquecode;
    private javax.swing.JTextField txtvehicleidentifier;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        txtname.setText(product.getName());
  txtgeographicdata.setText(product.getGeographicdata());
   String date_1 = String.valueOf(product.getDate());
     jDateChooser1.setText(date_1);
       
       //Telephone
      String tel = String.valueOf(product.getTelephone());
      txttelephone.setText(tel);
//        
//        //Fax
       String f = String.valueOf(product.getFax());
       txtfax.setText(f);
//        
       //Email
        txtemail.setText(product.getEmail());
//        
//        //ssn 
      String s = String.valueOf(product.getSsn());
     txtssn.setText(s);
       
//        //Medical Number
       String MedNum = String.valueOf(product.getMedicalnumber());
      txtmed.setText(MedNum);
//        
//        //Health Plan Number
   String Health = String.valueOf(product.getHealthplannumber());
   txthealthplannumber.setText(Health);
        
//        //Bank Account 
        txtbankaccount.setText(product.getBankaccount());
//        
//        //License
        txtlicense.setText(product.getLicense());
//        
//        //Vehicle
       txtvehicleidentifier.setText(product.getVehicleidentifier());
//        
//        //DeviceIdentifiers
        txtdeviceidentifiers.setText(product.getDeviceidentifiers());
//        
//        //LinkedIn
       txtlinkedIn.setText(product.getLinkedIn());
//        
//        //IP Address
   
      txtipaddress.setText(product.getIpaddress());
//        
//        //Unique Code
      txtuniquecode.setText(product.getUniquecode());
      PictureLabel.setIcon(product.getFilename());
//        
        
        
        
    }
}
